name: Bump versions

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */6 * * *

jobs:

  bump:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run versions.php script
        id: versions
        run: php ./versions.php >> $GITHUB_OUTPUT

      - name: Run apply-templates.sh script
        if: steps.versions.outputs.bumped == 1
        run: ./apply-templates.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        if: steps.versions.outputs.bumped == 1
        with:
          default_author: github_actions
          message: ${{ steps.versions.outputs.commit_message }}
          add: .
