name: Bump versions

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */6 * * *

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:

  bump:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # If not provided, the push from the EndBug/add-and-commit action won't trigger other workflows
          # see: https://github.com/EndBug/add-and-commit?tab=readme-ov-file#the-commit-from-the-action-is-not-triggering-ci
          token: ${{ secrets.GH_PERSONAL_TOKEN }}

      - name: Run versions.php script
        id: versions
        run: ./versions.php | tee -a $GITHUB_OUTPUT

      - name: Run apply-templates.sh script
        if: steps.versions.outputs.bumped == 1
        run: ./apply-templates.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        if: steps.versions.outputs.bumped == 1
        with:
          default_author: github_actions
          message: ${{ steps.versions.outputs.commit_message }}
          add: .
